services:
  pg:
    image: ghcr.io/louismollick/ichiran-postgres:latest
    build:
      dockerfile: ./docker/postgres-dockerfile
      context: .
      args:
        ICHIRAN_DB_URL: "https://github.com/tshatrov/ichiran/releases/download/ichiran-240107/jmdict-070124.pgdump"

  main:
    image: ghcr.io/louismollick/ichiran-http:latest
    build:
      dockerfile: ./docker/sbcl-dockerfile
      context: .