version: "3"

x-cloudmap:
  PrivateNamespace:
    ZoneName: ichiran

x-vpc:
  Properties:
    DHCPOptions:
      DomainName: ichiran

services:
  pg:
    ports:
      - 5432:5432/tcp
    image: ruiisuuu/ichiran_pg
    x-ecs:
      EnableExecuteCommand: true
    x-network:
      x-cloudmap: 
        PrivateNamespace:
          Port: 5432
      Ingress:
        Services:
          - Name: main
    build:
      dockerfile: ./docker/postgres-dockerfile
      context: .
      args:
        ICHIRAN_DB_URL: "https://github.com/tshatrov/ichiran/releases/download/ichiran-230122/ichiran-230122.pgdump"
    shm_size: "1gb"
    environment:
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${PWD}/docker/pgdata:/var/lib/postgresql/data

  main:
    image: ruiisuuu/ichiran_main
    x-ecs:
      EnableExecuteCommand: true
    x-network:
      x-cloudmap: PrivateNamespace
    build:
      dockerfile: ./docker/sbcl-dockerfile
      context: .
