version: "3"

services:
  main:
    build:
      dockerfile: ./docker/sbcl-dockerfile
      context: .
    environment:
      PGHOST: '<host>'
      ICHIRAN_CONNECTION: '("postgres" "postgres" "<password>" "<host>" :pooled-p t)'
