#!/bin/bash

set -e
sbcl --non-interactive --eval "(ql:quickload '#:cl+ssl/config)" \
                       --eval "(cl+ssl/config:define-libssl-path \"/usr/lib64/libssl.so.1.0.2k\")" \
                       --eval "(cl+ssl/config:define-libcrypto-path \"/usr/lib64/libcrypto.so.1.0.2k\")" \
                       --eval "(ql:quickload :ichiran)" \
                       --eval "(ichiran/mnt:add-errata)" \
                       --eval "(in-package :ichiran/all)" \
                       --eval "(init-all-caches)" \
                       --eval "(init-suffixes t)" \
                       --eval "(postmodern:clear-connection-pool)" \
                       --eval "(uiop:dump-image \"/root/ichiran.core\" :executable nil :compression t)"